### ISSUE TITLE
evans installing fails because of grpc-web-go-client

### ISSUE THREAD

**Issue by saboyutaka** [ktr0731/grpc-web-go-client#2]
When I tried to install evans, I got this message.

```
~ # go get github.com/ktr0731/evans
# github.com/ktr0731/grpc-web-go-client/grpcweb/grpcweb_reflection_v1alpha
/go/src/github.com/ktr0731/grpc-web-go-client/grpcweb/grpcweb_reflection_v1alpha/reflection.go:31:30: multiple-value c.cc.BidiStreaming() in single-value context
```

You changed `client.BidiStreaming` couple days ago 
https://github.com/ktr0731/grpc-web-go-client/commit/46586e16228da9d396a66bed1defb0bec33560fe#diff-7e67c0929808c88b228892ce33bcc737R289

But [here](grpc-web-go-client/grpcweb/grpcweb_reflection_v1alpha/reflection.go), still get single return variable.

Don't you forget update this?

**Comment by ktr0731** [comment]
Thank you for submitting this issue. (And I'm sorry, I couldn't notice that the issue was sent...)
This problem has been fixed past PR.
